name: Build assets
run-name: Build assets
on: [push, workflow_dispatch]
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: yarn

    - name: Build
      run: yarn build

    - name: Deploy to GitHub Pages              
      uses: JamesIves/github-pages-deploy-action@v4.5.0
      with:
        folder: build
